name: ser2net server
version: dev
slug: ser2net
description: >
  Expose serial ports over the network, including RFC2217 support
  for remote port settings change (e.g. baud rate or RTS)
url: https://github.com/misterblack1/addon-ser2net
codenotary: codenotary@johnhollowell.com
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ports:
  12345/tcp: 7000
  12346/tcp: 7001
ports_description:
  12345/tcp: "port to access serial device (tcp or telnet/rfc2217)"
  12346/tcp: "port to access admin interface (if enabled))"
uart: true # auto-map serial devices into the container
# usb: true
options:
  serial_device: /dev/ttyACM0
  max_connections: 4
  enable_admin_interface: true
  baud_rate: '460800'
  parity: "n"
  data_bits: '8'
  stop_bits: '1'
  protocol: tcp
  log_level: info
schema:
  serial_device: device(subsystem=tty)
  max_connections: int
  enable_admin_interface: bool
  baud_rate: list(300|1200|2400|4800|9600|19200|38400|57600|115200|460800)
  parity: list(n|e|o)
  data_bits: list(5|6|7|8)
  stop_bits: list(1|2)
  protocol: list(tcp|telnet|rfc2217)
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
